import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import {database } from '../firebaseConfig';
import {
  collection,
  getDocs,
  doc,
  setDoc,
} from 'firebase/firestore';
import {
  getAuth
}from 'firebase/auth';
import { useRouter } from 'next/router';
export default function Home() {
  const [TeamName, setName] = useState('');
  const [MemberCount, setAge] = useState(null);
  const auth = getAuth();
  const user = auth.currentUser;
  const databaseRef = collection(database,user.email);
  let router = useRouter()

  useEffect(() => {
    let token1 = sessionStorage.getItem('Token1')
    if (token1) {
      getData()
    }
    if (!token1) {
      router.push('/register')
    }
  }, [])

  const addData = () => {
    setDoc(doc(database,user.email,user.uid),{
      name: TeamName,
      count: Number(MemberCount)
    })
    setDoc(doc(database,"teams",TeamName),{
      r1q1:false,
      r1q2:false,
      r1q3:false,
      r3q1:false,
      r3q2:false,
      r3q3:false
    })
      .then(() => {
        alert('Data Sent')
        getData()
        setName('')
        setAge(null)
        router.push('/q1')
      })
      .catch((err) => {
        console.error(err);
      })
  }
  const next = () => {
        router.push('/q1')}

  const getData = async () => {
    await getDocs(databaseRef)
      .then((response) => {
        console.log(response.docs.map((data) => {
          return { ...data.data(), id: data.id }
        }))
      })
  }
  const logout = () => {
    sessionStorage.removeItem('Token1')
    sessionStorage.removeItem('user.email')
    sessionStorage.removeItem('user.uid')
    router.push('/login')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Next CRUD AUTH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button onClick={logout}>Log Out</button>
        </div>
        <h1>Home</h1>

        <input
          placeholder='Team Name'
          className={styles.inputBox}
          type="text"
          value={TeamName}
          onChange={event => setName(event.target.value)}
        />
        <input
          placeholder='member_count'
          className={styles.inputBox}
          type="number"
          value={MemberCount}
          onChange={event => setAge(event.target.value)}
        />

        
          <button
            className={styles.button}
            onClick={addData}
          >
            ADD
          </button>
          <hr />
          <h>if already created</h>
          <hr/>
          <button
          className={styles.button}
          onClick={next}
        >
          continue
        </button>
        
      </main>
    </div>
  )
}
